---
plugin:
  author: sample
  id: test_tool
  display: Test Tool Config
  version: 0.1.0
  upstream_project_url: https://puppet.com/docs/puppet/7/lang_template_epp.html

common:
  can_validate: false
  needs_write_access: false
  use_script: 'entrypoint'
  # No longer necessary as default args are handled in the scripts
  # default_args: []
  success_exit_code: 0
  interleave_stdout_err: false
